# Pandas 
**Pandas** is a popular library for data analysis built on top of the Python programming language. Pandas generally provide two data structures for manipulating data, They are: 
 
* DataFrame
* Series

A **DataFrame (df)**  is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.

* A Pandas DataFrame will be created by loading the datasets from existing storage. 
* Storage can be SQL Database, CSV file, Excel file, etc. 
* It can also be created from the lists, dictionaries, and from a list of dictionaries.

**Series** represents a one-dimensional array of indexed data.
It has two main components :
1. An array of actual data.
2. An associated array of indexes or data labels.

The index is used to access individual data values. You can also get a column of a dataframe as a **Series**. You can think of a Pandas series as a 1-D dataframe.

In [2]:
import pandas as pd
import numpy as np
import math

In [2]:
import pandas as pd

data = [10, 20, 30, 40, 50]
s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 
     'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
     'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [8]:
# replacing \ by / for file paths
a = r"C:\Users\himan\OneDrive\Desktop\Economics\Land use agriculture project\Book1.xlsx"
new = a.replace("\\","/")
new2 = r"C:\Users\himan\Downloads\people.csv"
print(new2)

C:\Users\himan\Downloads\people.csv

In [4]:
import pandas as pd
df = pd.read_excel(r"C:/Users/himan/OneDrive/Desktop/Economics/Land use agriculture project/Book1.xlsx")

display(df)
df.describe() #Generates statistics summary of numeric columns in the DataFrame.

,yield/hectare,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23,2023-24
0,rice,2391,2400,2494,2576,2638,2722,2717,2798,2838,2882
1,wheat,2750,3034,3200,3368,3533,3440,3521,3537,3521,3559
2,millets,1703,1579,1750,1934,1944,1991,2128,2251,2381,2283
3,cotton,462,415,512,443,378,455,451,428,443,436

,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23,2023-24
count,4.000000,4.000000,4.000000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,4.000000
mean,1826.500000,1857.000000,1989.000000,2080.250000,2123.25000,2152.000000,2204.250000,2253.500000,2295.750000,2290.000000
std,1008.071591,1130.903179,1148.940962,1239.091704,1332.96546,1276.658921,1300.825731,1326.186136,1321.012585,1341.415919
min,462.000000,415.000000,512.000000,443.000000,378.00000,455.000000,451.000000,428.000000,443.000000,436.000000
25%,1392.750000,1288.000000,1440.500000,1561.250000,1552.50000,1607.000000,1708.750000,1795.250000,1896.500000,1821.250000
50%,2047.000000,1989.500000,2122.000000,2255.000000,2291.00000,2356.500000,2422.500000,2524.500000,2609.500000,2582.500000
75%,2480.750000,2558.500000,2670.500000,2774.000000,2861.75000,2901.500000,2918.000000,2982.750000,3008.750000,3051.250000
max,2750.000000,3034.000000,3200.000000,3368.000000,3533.00000,3440.000000,3521.000000,3537.000000,3521.000000,3559.000000

In [85]:
df = pd.read_csv(r"C:\Users\himan\Downloads\people.csv")

df

      Name  Age  Country      Subject Languages
0    Alice   23  Britain           CS   English
1      Bob   24      USA   Civil Engg   English
2  Charlie   30  Ireland  Linguistics   English
3     Doge   18   Canada      Finance    French
4     Eric   32   Sweden           CS   Swedish
5     Fior   41    Italy         Math   Italian

## Accessing rows and columns of data

> *Keep in mind that row and column indexes start from 0*

**Columns** can be accessed by using column title / label as <code> df['column_name'] </code>, and to access multiple columns, enclose the column names within dual square braces[]. To find unique elements within a column use <code> df['colum_name'].unique() </code> . Further elements can be filtered via inequalities like <code> df[df['Age'] > 25] </code> 

**Rows** can be accessed using the iloc method as <code> df.iloc[0] </code> which takes one or two index as input. Or the <code> .loc['Name'] </code> can be used as well 

**Crucial difference** between `.loc[]` and `.iloc[]` methods

 - `.iloc[0:2]` gets positions 0 and 1 (stop=2 excluded)
 - `.loc['Alice':'Charlie']` gets Alice, Bob, AND Charlie (both endpoints included)

In [14]:
df = pd.read_csv(r"C:\Users\himan\Downloads\people.csv")

#for accessing multiple columns use double brackets [[]]
print(df['Age']) #accessing column via column title

print(df.iloc[0]) #accessing row via iloc method

print(df[df['Age']>24]) 

print(df['Languages'].unique())

i = 0
for i in range(len(df['Age'])):
    L_age = df["Age"]
    L_name = df["Name"]
    if L[i] > 24 :
      print(f" {L_name[i]}  Is older than Himanshu")
   # i = i + 1

0    23
1    24
2    30
3    18
4    32
5    41
Name: Age, dtype: int64
Name           Alice
Age               23
Country      Britain
Subject           CS
Languages    English
Name: 0, dtype: object
      Name  Age  Country      Subject Languages
2  Charlie   30  Ireland  Linguistics   English
4     Eric   32   Sweden           CS   Swedish
5     Fior   41    Italy         Math   Italian
['English' 'French' 'Swedish' 'Italian']
 Charlie  Is older than Himanshu
 Eric  Is older than Himanshu
 Fior  Is older than Himanshu

## Slicing Dataframes 

Dataframes can be sliced to get desired rows and columns as output. Indexing by labels(i.e. using <code>loc()</code>) differs from indexing by integers (i.e. using <code>iloc()</code>). With <code>loc()</code>, both the start bound and the stop bound are inclusive. When using <code>loc()</code>, integers can be used, but the integers refer to the index label and not the position. 


See the <code> .iloc </code> and <code> .loc </code> method below

In [81]:
print(df.iloc[0:2, 0:3], '\n ' )

print(df.loc[1:2 , 'Subject':'Languages'])

    Name  Age  Country
0  Alice   23  Britain
1    Bob   24      USA

       Subject Languages
1   Civil Engg   English
2  Linguistics   English

In [50]:
# just a fun problem to solve
list_occur = [1, 2, 4, 2, 5, 2, 2, 4, 1, 4, 3, 4, 2, 4 , 5, 1]

dict1 = {}

for i in list_occur:
    dict1[i] = list_occur.count(i)

print(dict1)
pd.Series(dict1)

{1: 3, 2: 5, 4: 5, 5: 2, 3: 1}

1    3
2    5
4    5
5    2
3    1
dtype: int64